name: saut_enma_bloc
description: A declarative router for Flutter. Navigate by enum, argument passing type Map, with latest flutter_bloc dependency.
version: 0.15.0
homepage: https://github.com/thanhle1547/flutter_simple_app_router/tree/main/enum_name_map_arg_bloc

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
