name: saut_enma_bloc
description: A declarative router for Flutter. Navigate by enum, argument passing type Map, with latest flutter_bloc dependency.
version: 0.2.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
